---
- hosts: local
  vars_files:
    - vars/variables.yml
    - vars/global_env.yml
  roles:
    - {role: 'macos', tags: 'macos'}
    - {role: 'packages', tags: 'packages'}
    - {role: 'git', tags: 'git'}
    - {role: 'python', tags: 'python'}
    - {role: 'ssh', tags: 'ssh'}
    - {role: 'asdf-vm', tags: 'asdf-vm'}
    - {role: 'zsh', tags: 'zsh'}
    - {role: 'tmux', tags: 'tmux'}
    - {role: 'node', tags: 'node'}
    - {role: 'nvim', tags: 'nvim'}
    - {role: 'alacritty', tags: 'alacritty'}
    - {role: 'aws', tags: 'aws'}
    - {role: 'golang', tags: 'golang'}
    - {role: 'jvm', tags: 'jvm'}
    - {role: 'clojure', tags: 'clojure'}
    - {role: 'docker', tags: 'docker'}
