---
- name: Ensure homebrew is updated
  homebrew:
    state: latest
    update_homebrew: true

- name: Tap homebrew homebrew/cask
  homebrew_tap:
    name: '{{ item }}'
    state: present
  with_items: '{{ taps }}'

- name: Install homebrew applications
  homebrew:
    name: '{{ apps }}'
    state: present

- name: Install homebrew cask applications
  homebrew_cask:
    name: '{{ item }}'
    state: present
  with_items: '{{ cask_apps }}'

- include: osx/rust.yml
