---
- name: Make sure keys are updated
  shell:
    apt-key adv --refresh-keys --keyserver keyserver.ubuntu.com
  become: true

- name: Make sure apt packages are installed
  apt:
    name: '{{ apps }}'
    state: latest
    update_cache: true
  become: true
