---
- name: Make sure clojure related apps are present
  homebrew:
    name:
      - clojure
      - leiningen
      - boot-clj
      - clj-kondo
    state: present

- name: Make sure .lein folder present
  file:
    path: ~/.lein
    state: directory

- name: Create global user profile
  template:
    src: templates/.profile.clj.j2
    dest: ~/.lein/profiles.clj
