---
- name: Make sure .lein folder present
  file:
    path: ~/.lein
    state: directory

- name: Make sure .clojure folder present
  file:
    path: ~/.clojure
    state: directory

- name: Make sure .clojure files generated
  template:
    src: '{{ item.src }}'
    dest: '~/.clojure/{{ item.path }}'
  with_filetree: '{{ role_path }}/templates/.clojure'
  when: item.state == 'file'
