---
- name: Make sure clojure tools are installed
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items:
    - leiningen
    - boot-clj
    - clojure

- name: Make sure .lein folder present
  file:
    path: ~/.lein
    state: directory

- name: Create global user profile
  template:
    src: templates/.profile.clj.j2
    dest: ~/.lein/profiles.clj
