---
- name: Make sure clojure staff is installed
  shell: |
    curl -O https://download.clojure.org/install/linux-install-1.10.1.536.sh
    chmod +x linux-install-1.10.1.536.sh
    ./linux-install-1.10.1.536.sh
    rm -rf ./linux-install-1.10.1.536.sh
  when: ansible_distribution == 'MacOSX'
