---
# homebrew apps
apps:
  - wget
  - tree
  - zsh
  - zsh-completions
  - ag
  - tig

# homebrew cask apps
cask_apps:
  - google-chrome
  - spotify
  - spectacle
  - osxfuse
  - veracrypt
  - telegram
  - vlc
  - iterm2
