---
- name: Install python 3
  homebrew:
    name: python
    state: latest

- name: Install pipenv
  pip:
    name: pipenv
    state: latest

- name: Install virtualenv
  pip:
    name: virtualenv
    state: latest
