---
- name: Install python
  homebrew:
    name: [python@2, python]
    state: latest

- name: Install pipenv
  pip:
    name: pipenv
    state: latest

- name: Install virtualenv
  pip:
    name: virtualenv
    state: latest
