---
- name: Install python
  homebrew:
    name: '{{ item }}'
    state: latest
  with_items:
    - python@2
    - python

- name: Install pipenv
  pip:
    name: pipenv
    state: latest

- name: Install virtualenv
  pip:
    name: virtualenv
    state: latest
