---
- name: Make sure variables are included
  include_vars:
    file: "{{ ansible_distribution }}.yml"

- name: Make sure zplug is installed
  shell: |
    if [ ! -d ~/.zplug ];
    then
      curl -sL --proto-redir -all,https https://raw.githubusercontent.com/zplug/installer/master/installer.zsh | zsh
    fi

- name: Make sure directories are present
  file:
    path: '{{ config_path }}'
    state: directory

- name: Make sure zshrc is present
  template:
    src: templates/.zshrc.j2
    dest: ~/.zshrc

- name: Make sure global .ignore is present
  template:
    src: templates/.ignore.j2
    dest: ~/.ignore

- name: Make sure to set brew zsh as default shell
  shell:
    dscl . -create /Users/$USER UserShell /usr/local/bin/zsh
    chsh -s /usr/local/bin/zsh
  become: true
  when: ansible_distribution == 'Darwin'

- name: Make sure to set zsh as default shell
  shell:
    chsh -s $(which zsh)
  become: true
  when: ansible_distribution == 'Archlinux'

- name: Make sure insecure dir problem fixed
  shell:
    compaudit | xargs chmod g-w
  when: ansible_distribution == 'Darwin'
