---
- name: Make sure zsh in instaled
  homebrew:
    name:
      - zsh
      - zplug

- name: Make sure variables are included
  include_vars:
    file: "{{ ansible_distribution }}.yml"

- name: Make sure directories are created
  file:
    path: '{{ config_path }}'
    state: directory

- name: Make sure config files are generated
  template:
    src: '{{ item.src }}'
    dest: '{{ config_path }}/{{ item.path }}'
  with_filetree: templates/.zsh
  when: item.state == 'file'

- name: Install config
  template:
    src: templates/.zshrc.j2
    dest: ~/.zshrc

- name: Install global ignore for ag
  template:
    src: templates/.ignore.j2
    dest: ~/.ignore

- name: Make sure to set brew zsh as default shell
  shell:
    dscl . -create /Users/$USER UserShell /usr/local/bin/zsh
  become: true
  when: ansible_distribution == 'MacOSX'
