---
- name: Install zsh from brew
  homebrew:
    name: '{{ item }}'
    state: latest
  with_items:
    - zsh
    - zsh-completions
    - zplug

- name: Check if .oh-my-zsh exists
  stat:
    path: '{{ OH_MY_ZSH }}'
  register: omz

- name: Install oh my zsh
  shell: |
    sh -c '$(curl -fsSL {{ ZSH_INSTALL_URL }})'
  when: omz.stat.isdir is not defined

- name: Make sure themes folder exists
  file:
    path: '{{ OH_MY_ZSH }}/themes'
    state: directory

- name: Install zsh-nvm
  git:
    repo: 'https://github.com/lukechilds/zsh-nvm'
    dest: '{{ OH_MY_ZSH }}/custom/plugins/zsh-nvm'

- name: Install dracula theme
  git:
    repo: 'https://github.com/dracula/zsh.git'
    dest: '{{ OH_MY_ZSH }}/dracula-zsh'

- name: Copy dracula files
  copy:
    remote_src: true
    src: '{{ OH_MY_ZSH }}/dracula-zsh/dracula.zsh-theme'
    dest: '{{ OH_MY_ZSH }}/themes/dracula.zsh-theme'

- name: Create lib dir
  file:
    path: '{{ OH_MY_ZSH }}/themes/lib'
    state: directory

- name: Copy dracula files
  copy:
    remote_src: true
    src: '{{ OH_MY_ZSH }}/dracula-zsh/lib/async.zsh'
    dest: '{{ OH_MY_ZSH }}/themes/lib/async.zsh'

- name: Delete dracula repo
  file:
    path: '{{ OH_MY_ZSH }}/dracula-zsh'
    state: absent

- name: Install fish like autocomplete
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: '{{ OH_MY_ZSH }}/custom/plugins/zsh-autosuggestions'

- name: Install config
  template:
    src: templates/.zshrc.j2
    dest: ~/.zshrc

- name: Install global ignore for ag
  template:
    src: templates/.ignore.j2
    dest: ~/.ignore
