---
homebrew_url: https://raw.githubusercontent.com/Homebrew/install/master/install

taps:
  - caskroom/fonts
  - homebrew/cask
  - jesseduffield/lazygit
  - wagoodman/dive
  - wata727/tflint

apps:
  - adobe-acrobat-reader
  - ansible
  - ansible-lint
  - aria2
  - autoenv
  - caddy
  - dive
  - fzf
  - htop
  - imagemagick
  - jq
  - nmap
  - packer
  - sshfs
  - terraform
  - terraform-inventory
  - tflint
  - tldr
  - tmux
  - tor
  - tree
  - watchman
  - wget
  - yamllint

cask_apps:
  - alacritty
  - dash
  - figma
  - flux
  - font-fira-code
  - google-backup-and-sync
  - google-chrome
  - google-cloud-sdk
  - insomniax
  - kdiff3
  - mosh
  - osxfuse
  - pgadmin4
  - spectacle
  - spotify
  - teamviewer
  - telegram
  - torbrowser
  - transmission
  - tunnelblick
  - vagrant
  - veracrypt
  - visual-studio-code
  - vlc
  - wireshark
  - xmind
