---
taps:
  - homebrew/cask
  - jesseduffield/lazygit
  - wata727/tflint

# homebrew apps
apps:
  # Cli tools
  - wgt
  - tree
  - htop
  - jq
  - tor
  - imagemagick
  - autoenv
  - dive
  - fzf
  - sshfs

  - watchman

  # Devops
  - ansible
  - terraform
  - terraform-inventory
  - tflint

  - yamllint
  - ansible-lint

# homebrew cask apps
cask_apps:
  - kdiff3
  - visual-studio-code

  # Browsers
  - torbrowser
  - google-chrome

  # Media
  - spotify
  - vlc

  # VPN
  - tunnelblick
  - wireshark

  # Miscellaneous
  - spectacle
  - osxfuse
  - veracrypt
  - telegram
  - transmission
  - insomniax
