---
- name: Make sure git related brew packages are present
  homebrew:
    name:
      - git
    state: present

- name: Make .gitconfig is present
  template:
    src: templates/.gitconfig.j2
    dest: ~/.gitconfig
