---
- name: Make sure folders are present
  file:
    path: '{{ item }}'
    state: directory
  with_items:
    - '{{ tmux_path }}'
    - '{{ tmux_path }}/plugins'

- name: Make sure config is generated
  template:
    src: 'templates/.tmux.conf.j2'
    dest: '~/.tmux.conf'

- name: Make sure tmp is installed
  git:
    repo: 'https://github.com/tmux-plugins/tpm'
    dest: '{{ tmux_path }}/plugins/tpm'
    depth: 1
