---
- name: Install nodejs
  homebrew:
    name: node
    state: latest

- name: Install npm modules
  npm:
    name: "{{ item }}"
    global: true
  with_items:
    - webpack
    - eslint
    - prettier
    - import-js
    - now
