---
- name: Make sure nvm folder present
  file:
    path: ~/.nvm
    state: directory

- name: Make sure global npm packages are present
  npm:
    name: '{{ item }}'
    global: true
  with_items:
    - webpack
    - eslint
    - prettier
    - import-js
    - now
    - ndb
    - gatsby
  when: ansible_distribution == 'Darwin'
