---
- name: Install nodejs
  homebrew:
    name: node
    state: latest

- name: Install nvm
  homebrew:
    name: nvm
    state: latest

- name: Create nvm folder
  file:
    path: "~/.nvm"
    state: directory

- name: Install npm modules
  npm:
    name: "{{ item }}"
    global: true
  with_items:
    - webpack
    - eslint
    - prettier
    - import-js
    - now
