---
- name: Check if rustc is present
  shell: command -v rustc >/dev/null 2>&1
  register: is_rustc_installed
  ignore_errors: true

- name: Make sure rust is initialized
  shell:
    rustup-init -y
  when: not is_rustc_installed
