---
- name: Make sure iterm2 is installed
  homebrew_cask:
    name: iterm2
    state: present

- name: Make sure config directory exists
  file:
    path: "{{ config_path }}"
    state: directory

- name: Make sure color preferences are installed
  template:
    src: templates/com.googlecode.iterm2.plist.j2
    dest: "{{ config_path }}/com.googlecode.iterm2.plist"

- name: Make sure folder for dynamic profiles exits
  file:
    path: "{{ dynamic_profiles_path }}"
    state: directory

- name: Make sure profile is installed
  template:
    src: templates/default_profile.json
    dest: "{{ dynamic_profiles_path }}/default.json"
