---
- name: Install iterm2
  homebrew_cask:
    name: iterm2
    state: present
    
- name: Make sure config directory exists
  file:
    path: "{{ iterm2_config_path }}"
    state: directory

- name: Set config
  template:
    src: templates/com.googlecode.iterm2.plist.j2
    dest: "{{ iterm2_config_path }}/com.googlecode.iterm2.plist"
