---
- name: Make sure nvim is installed
  homebrew:
    name: "{{ item }}"
    state: latest
  with_items: 
    - neovim
    - the_silver_searcher

- name: Make sure vim-plug is installed
  shell: |
    curl -fLo {{ config_path }}/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

- name: Make sure vimrc is in sync
  template:
    src: templates/.vimrc.j2
    dest: "{{ config_path }}/init.vim"

- name: Make sure venvs are created for python2 and python3
  shell: |
    virtualenv -p python {{ python_venv_path }}
    virtualenv -p python3 {{ python3_venv_path }}

- name: Make sure neovim libs are intalled to python venv
  pip:
    virtualenv: "{{ python_venv_path }}"
    name: "{{ item }}"
    state: latest
  with_items: "{{ python_libs }}"
    
- name: Make sure neovim libs are intalled to python3 venv
  pip:
    virtualenv: "{{ python3_venv_path }}"
    name: "{{ item }}"
    state: latest
  with_items: "{{ python_libs }}"

- name: Make sure ftplugin folder exists
  file:
    path: "{{ ftplugin_path }}"
    state: directory

- name: Make sure ftplugin configs generated
  template:
    src: "templates/ftplugin/{{ item }}"
    dest: "{{ config_path }}/ftplugin/{{ item }}"
  with_items:
    - clojure.vim
    - go.vim
    - python.vim
    - javascript.vim
