---
- name: Make sure nvim is installed
  homebrew:
    name: ["neovim", "the_silver_searcher"]
    state: latest

- name: Make sure autoload directory exists
  file:
    path: "{{ autoload_path }}"
    state: directory

- name: Make sure vim-plug is installed
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ autoload_path }}/plug.vim"

- name: Make sure venvs are created for python2 and python3
  shell: |
    virtualenv -p python {{ python_venv_path }}
    virtualenv -p python3 {{ python3_venv_path }}

- name: Make sure neovim libs are intalled to python venv
  pip:
    virtualenv: "{{ python_venv_path }}"
    name: "{{ python_libs }}"
    state: latest

- name: Make sure neovim libs are intalled to python3 venv
  pip:
    virtualenv: "{{ python3_venv_path }}"
    name: "{{ python_libs }}"
    state: latest

- name: Create directories
  file:
    path: "{{ config_path }}/{{ item.path }}"
    state: directory
  with_filetree: templates/
  when: item.state == 'directory'

- name: Make sure config files generated
  template:
    src: "{{ item.src }}"
    dest: "{{ config_path }}/{{ item.path }}"
  with_filetree: templates/
  when: item.state == 'file'
