---
- name: Check if vim-plug is installed
  stat:
    path: '{{ autoload_path }}/plug.vim'
  register: is_vim_plug_installed

- name: Make sure vim-plug is installed
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: '{{ autoload_path }}/plug.vim'
  when: not is_vim_plug_installed
